### ISSUE TITLE
How to change fontFamily?

### ISSUE THREAD

**Issue by xempie** [hannigand/react-native-ui-stepper#10]
Thanks for providing this. Is there any way to set the fontFamily for the number?

**Comment by hannigand** [comment]
Modifying the fontFamily is not supported right now. 

I will add the ability to change it this evening.

**Comment by xempie** [comment]
Has this feature been released?
I'm waiting to use it in my app but just have fontFamily issue.
Thanks

**Comment by hannigand** [comment]
Sorry for going stale, let's get this feature shipped today 🚢

**Comment by hannigand** [comment]
I've shipped this feature as part of `1.2.3`. I've updated both examples on Android and iOS to demonstrate the usage of a custom font family.

You can add a `fontFamily` prop which expects a String. Should you not provide a prop, the `System` font will be used.
