### ISSUE TITLE
Is it possible to change value from  outside?

### ISSUE THREAD

**Issue by iiqmohamad** [hannigand/react-native-ui-stepper#11]
Hi @hannigand , thanks for this component.

Sometime, we need to update the value based on state / redux. is there a way to make it happend?
I only see the initialValue props

**Comment by hannigand** [comment]
I suppose that you could use the `initialValue` prop, but as naming conventions go, that's a little confusing. 

I will add a `value` property to achieve this. I need to fix a couple of UI issues too and will release this as `1.2.4` in the up coming days/weeks.

**Comment by hannigand** [comment]
There will be a `value` prop added to the UIStepper. The `initialValue` property will be used when the component is instantiated. After that, the `value` property will be used.

If you are to use it, you are responsible for ensuring ensuring that you use a correct value. 

Here's something that might be trivial, but I will document it anyway.

```javascript
class Foo extends React.Component {
  constructor() {
    super();
    this.state = { value: 0 }
  }
  componentDidMount() {
    setInterval(() => {
      this.setState({ value: this.state.value + 1 });
    }, 1500);
  }
  render() {
    const { value } = this.state;
    return (
      <UIStepper 
        displayValue 
        initialValue={0} 
        value={this.state.value} 
      />
    )
  }
} 
```
Whilst this will work and update the value every 1.5 seconds, when you press the Increment (+) and Decrement buttons (-), you must make sure you modify the state variable. 

If you don't, you will have some unwanted problems:

![untitled](https://user-images.githubusercontent.com/5614282/34265413-b763e9e0-e66d-11e7-8340-f6e8db2a8ca8.gif)

```javascript
class Foo extends React.Component {
  constructor() {
    super();
    this.state = { value: 0 }
  }
  componentDidMount() {
    setInterval(() => {
      this.setState({ value: this.state.value + 1 });
    }, 1500);
  }
  increment = () => {
    this.setState({ value: this.state.value + 1 });
  }
  decrement = () => {
    this.setState({ value: this.state.value - 1 });
  }
  render() {
    const { value } = this.state;
    return (
      <UIStepper 
        displayValue 
        initialValue={0} 
        value={this.state.value} 
        onIncrement={this.increment}
        onDecrement={this.decrement}
      />
    )
  }
} 
```

This will be shipped in 1.2.4 along with the ability to setValue via a `ref`.

```javascript
<UIStepper innerRef={ stepper = { this.stepper = stepper } } />
<Button
  title="Set value to 50"
  onPress={() => { this.stepper.setValue(50) }}
/>
```

**Comment by iiqmohamad** [comment]
@hannigand perfect,That's exactly what I mean. 

Thanks a lot, waiting for this realease :+1:

**Comment by hannigand** [comment]
@iiqmohamad - 1.2.4 now is available 🎉
