### ISSUE TITLE
How can I reset the UI Stepper Value

### ISSUE THREAD

**Issue by sharmad1205** [hannigand/react-native-ui-stepper#14]
I am using three ui-stepper in flatlist. 
When I change the value from dropdown I want to reset the values of the list
other values are reset but
the stepper value takes the previous and increment the value in that
E.g Suppose I have two stepper inside a FlatList 
1. Ten_Counter (step value 10)
2. Twenty_Counter(step value 20)

I have a dropbox outside the list, When I select VALUE1 from dropbox
and increment Ten_Counter It works fine

but when I select VALUE2 from dropbox the list refreshed(not UI)
again when I clicked the Ten_Counter It increments with the previous value and give 20

Please help me finding a solution for
Resetting the value of a counter

**Comment by hannigand** [comment]
Hey @sharmad1205 thanks for raising this.

I will add a function which can be used to reset the counter.

**Comment by hannigand** [comment]
I have added a `innerRef` prop which will give you access to class methods. It uses the principles of [refs](https://reactjs.org/docs/refs-and-the-dom.html) in React.

```javascript
<UIStepper 
  displayValue
  innerRef={stepper => { this.stepper = stepper }} 
/>
<Button 
  title="Reset"
  onPress={() => {
    this.stepper.resetValue();
  }}
/>
```

This ref also gives you access to:

`increment()`
`decrement()`
`setValue()`

There are other methods, but they are intended for internal use only.

I will ship this as part of 1.2.4 🚢  but this will be done when I implement the other open issue 🛠️

**Comment by hannigand** [comment]
@sharmad1205 - 1.2.4 is now available 🎉

**Comment by sharmad1205** [comment]
Great Work! Its Working now...
Thanks for the Support....
